// Code generated by entc, DO NOT EDIT.

package carutility

const (
	// Label holds the string label denoting the carutility type in the database.
	Label = "car_utility"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCars holds the string denoting the cars edge name in mutations.
	EdgeCars = "cars"
	// Table holds the table name of the carutility in the database.
	Table = "car_utilities"
	// CarsTable is the table that holds the cars relation/edge. The primary key declared below.
	CarsTable = "car_car_utilities"
	// CarsInverseTable is the table name for the Car entity.
	// It exists in this package in order to avoid circular dependency with the "car" package.
	CarsInverseTable = "cars"
)

// Columns holds all SQL columns for carutility fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// CarsPrimaryKey and CarsColumn2 are the table columns denoting the
	// primary key for the cars relation (M2M).
	CarsPrimaryKey = []string{"car_id", "car_utility_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
)
