version: '3'

services:
  mysql:
    image: mysql
    container_name: local-mysql-database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Lengkong123_

volumes:
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/louisaldorio/data-mysql'
      # device: '/home/louisaldorio/droplet-backup/louisaldorio/data-mysql'