// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"myapp/ent/car"
	"myapp/ent/carutility"
	"myapp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CarUtilityQuery is the builder for querying CarUtility entities.
type CarUtilityQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CarUtility
	// eager-loading edges.
	withCars *CarQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CarUtilityQuery builder.
func (cuq *CarUtilityQuery) Where(ps ...predicate.CarUtility) *CarUtilityQuery {
	cuq.predicates = append(cuq.predicates, ps...)
	return cuq
}

// Limit adds a limit step to the query.
func (cuq *CarUtilityQuery) Limit(limit int) *CarUtilityQuery {
	cuq.limit = &limit
	return cuq
}

// Offset adds an offset step to the query.
func (cuq *CarUtilityQuery) Offset(offset int) *CarUtilityQuery {
	cuq.offset = &offset
	return cuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cuq *CarUtilityQuery) Unique(unique bool) *CarUtilityQuery {
	cuq.unique = &unique
	return cuq
}

// Order adds an order step to the query.
func (cuq *CarUtilityQuery) Order(o ...OrderFunc) *CarUtilityQuery {
	cuq.order = append(cuq.order, o...)
	return cuq
}

// QueryCars chains the current query on the "cars" edge.
func (cuq *CarUtilityQuery) QueryCars() *CarQuery {
	query := &CarQuery{config: cuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(carutility.Table, carutility.FieldID, selector),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, carutility.CarsTable, carutility.CarsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CarUtility entity from the query.
// Returns a *NotFoundError when no CarUtility was found.
func (cuq *CarUtilityQuery) First(ctx context.Context) (*CarUtility, error) {
	nodes, err := cuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{carutility.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cuq *CarUtilityQuery) FirstX(ctx context.Context) *CarUtility {
	node, err := cuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CarUtility ID from the query.
// Returns a *NotFoundError when no CarUtility ID was found.
func (cuq *CarUtilityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{carutility.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cuq *CarUtilityQuery) FirstIDX(ctx context.Context) int {
	id, err := cuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CarUtility entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one CarUtility entity is not found.
// Returns a *NotFoundError when no CarUtility entities are found.
func (cuq *CarUtilityQuery) Only(ctx context.Context) (*CarUtility, error) {
	nodes, err := cuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{carutility.Label}
	default:
		return nil, &NotSingularError{carutility.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cuq *CarUtilityQuery) OnlyX(ctx context.Context) *CarUtility {
	node, err := cuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CarUtility ID in the query.
// Returns a *NotSingularError when exactly one CarUtility ID is not found.
// Returns a *NotFoundError when no entities are found.
func (cuq *CarUtilityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = &NotSingularError{carutility.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cuq *CarUtilityQuery) OnlyIDX(ctx context.Context) int {
	id, err := cuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CarUtilities.
func (cuq *CarUtilityQuery) All(ctx context.Context) ([]*CarUtility, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cuq *CarUtilityQuery) AllX(ctx context.Context) []*CarUtility {
	nodes, err := cuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CarUtility IDs.
func (cuq *CarUtilityQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := cuq.Select(carutility.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cuq *CarUtilityQuery) IDsX(ctx context.Context) []int {
	ids, err := cuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cuq *CarUtilityQuery) Count(ctx context.Context) (int, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cuq *CarUtilityQuery) CountX(ctx context.Context) int {
	count, err := cuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cuq *CarUtilityQuery) Exist(ctx context.Context) (bool, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cuq *CarUtilityQuery) ExistX(ctx context.Context) bool {
	exist, err := cuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CarUtilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cuq *CarUtilityQuery) Clone() *CarUtilityQuery {
	if cuq == nil {
		return nil
	}
	return &CarUtilityQuery{
		config:     cuq.config,
		limit:      cuq.limit,
		offset:     cuq.offset,
		order:      append([]OrderFunc{}, cuq.order...),
		predicates: append([]predicate.CarUtility{}, cuq.predicates...),
		withCars:   cuq.withCars.Clone(),
		// clone intermediate query.
		sql:  cuq.sql.Clone(),
		path: cuq.path,
	}
}

// WithCars tells the query-builder to eager-load the nodes that are connected to
// the "cars" edge. The optional arguments are used to configure the query builder of the edge.
func (cuq *CarUtilityQuery) WithCars(opts ...func(*CarQuery)) *CarUtilityQuery {
	query := &CarQuery{config: cuq.config}
	for _, opt := range opts {
		opt(query)
	}
	cuq.withCars = query
	return cuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CarUtility.Query().
//		GroupBy(carutility.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cuq *CarUtilityQuery) GroupBy(field string, fields ...string) *CarUtilityGroupBy {
	group := &CarUtilityGroupBy{config: cuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.CarUtility.Query().
//		Select(carutility.FieldName).
//		Scan(ctx, &v)
//
func (cuq *CarUtilityQuery) Select(fields ...string) *CarUtilitySelect {
	cuq.fields = append(cuq.fields, fields...)
	return &CarUtilitySelect{CarUtilityQuery: cuq}
}

func (cuq *CarUtilityQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cuq.fields {
		if !carutility.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cuq.path != nil {
		prev, err := cuq.path(ctx)
		if err != nil {
			return err
		}
		cuq.sql = prev
	}
	return nil
}

func (cuq *CarUtilityQuery) sqlAll(ctx context.Context) ([]*CarUtility, error) {
	var (
		nodes       = []*CarUtility{}
		_spec       = cuq.querySpec()
		loadedTypes = [1]bool{
			cuq.withCars != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CarUtility{config: cuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, cuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := cuq.withCars; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*CarUtility, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Cars = []*Car{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*CarUtility)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   carutility.CarsTable,
				Columns: carutility.CarsPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(carutility.CarsPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, cuq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "cars": %w`, err)
		}
		query.Where(car.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "cars" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Cars = append(nodes[i].Edges.Cars, n)
			}
		}
	}

	return nodes, nil
}

func (cuq *CarUtilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cuq.querySpec()
	return sqlgraph.CountNodes(ctx, cuq.driver, _spec)
}

func (cuq *CarUtilityQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cuq *CarUtilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   carutility.Table,
			Columns: carutility.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carutility.FieldID,
			},
		},
		From:   cuq.sql,
		Unique: true,
	}
	if unique := cuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carutility.FieldID)
		for i := range fields {
			if fields[i] != carutility.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cuq *CarUtilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cuq.driver.Dialect())
	t1 := builder.Table(carutility.Table)
	columns := cuq.fields
	if len(columns) == 0 {
		columns = carutility.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cuq.sql != nil {
		selector = cuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range cuq.predicates {
		p(selector)
	}
	for _, p := range cuq.order {
		p(selector)
	}
	if offset := cuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CarUtilityGroupBy is the group-by builder for CarUtility entities.
type CarUtilityGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cugb *CarUtilityGroupBy) Aggregate(fns ...AggregateFunc) *CarUtilityGroupBy {
	cugb.fns = append(cugb.fns, fns...)
	return cugb
}

// Scan applies the group-by query and scans the result into the given value.
func (cugb *CarUtilityGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cugb.path(ctx)
	if err != nil {
		return err
	}
	cugb.sql = query
	return cugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: CarUtilityGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) StringsX(ctx context.Context) []string {
	v, err := cugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilityGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) StringX(ctx context.Context) string {
	v, err := cugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: CarUtilityGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) IntsX(ctx context.Context) []int {
	v, err := cugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilityGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) IntX(ctx context.Context) int {
	v, err := cugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: CarUtilityGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilityGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: CarUtilityGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *CarUtilityGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilityGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cugb *CarUtilityGroupBy) BoolX(ctx context.Context) bool {
	v, err := cugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cugb *CarUtilityGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cugb.fields {
		if !carutility.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cugb *CarUtilityGroupBy) sqlQuery() *sql.Selector {
	selector := cugb.sql.Select()
	aggregation := make([]string, 0, len(cugb.fns))
	for _, fn := range cugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cugb.fields)+len(cugb.fns))
		for _, f := range cugb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cugb.fields...)...)
}

// CarUtilitySelect is the builder for selecting fields of CarUtility entities.
type CarUtilitySelect struct {
	*CarUtilityQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cus *CarUtilitySelect) Scan(ctx context.Context, v interface{}) error {
	if err := cus.prepareQuery(ctx); err != nil {
		return err
	}
	cus.sql = cus.CarUtilityQuery.sqlQuery(ctx)
	return cus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cus *CarUtilitySelect) ScanX(ctx context.Context, v interface{}) {
	if err := cus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Strings(ctx context.Context) ([]string, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: CarUtilitySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cus *CarUtilitySelect) StringsX(ctx context.Context) []string {
	v, err := cus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilitySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cus *CarUtilitySelect) StringX(ctx context.Context) string {
	v, err := cus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Ints(ctx context.Context) ([]int, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: CarUtilitySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cus *CarUtilitySelect) IntsX(ctx context.Context) []int {
	v, err := cus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilitySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cus *CarUtilitySelect) IntX(ctx context.Context) int {
	v, err := cus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: CarUtilitySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cus *CarUtilitySelect) Float64sX(ctx context.Context) []float64 {
	v, err := cus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilitySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cus *CarUtilitySelect) Float64X(ctx context.Context) float64 {
	v, err := cus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: CarUtilitySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cus *CarUtilitySelect) BoolsX(ctx context.Context) []bool {
	v, err := cus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cus *CarUtilitySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{carutility.Label}
	default:
		err = fmt.Errorf("ent: CarUtilitySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cus *CarUtilitySelect) BoolX(ctx context.Context) bool {
	v, err := cus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cus *CarUtilitySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cus.sql.Query()
	if err := cus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
