// Code generated by entc, DO NOT EDIT.

package ent

import (
	"myapp/ent/carutility"
	"myapp/ent/group"
	"myapp/ent/schema"
	"myapp/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	carutilityFields := schema.CarUtility{}.Fields()
	_ = carutilityFields
	// carutilityDescName is the schema descriptor for name field.
	carutilityDescName := carutilityFields[0].Descriptor()
	// carutility.DefaultName holds the default value on creation for the name field.
	carutility.DefaultName = carutilityDescName.Default.(string)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
